//
// Created by Dhanushka on 11/16/18.
//

/*
** 2001 September 15
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** This file contains code to implement a pseudo-random number
** generator (PRNG) for SQLite.
**
** Random numbers are used by some of the database backends in order
** to generate random integer keys for tables or random filenames.
**
** $Id: random.c,v 1.10 2002/02/19 13:39:23 drh Exp $
**
** 2001年9月15日
**
** 作者放弃此源代码的版权。作为法律声明的替代，这里有一个祝福：
**
**    愿你行善而不作恶。
**    愿你宽恕自己并宽恕他人。
**    愿你自由分享，索取不超所予。
**
** *************************************************************************
** 此文件包含实现SQLite伪随机数生成器（PRNG）的代码。
**
** 一些数据库后端使用随机数来生成表的随机整数键或随机文件名。
*/
#include "sqliteInt.h"
#include "os.h"


/*
** Get a single 8-bit random value from the RC4 PRNG.  The Mutex
** must be held while executing this routine.
**
** Why not just use a library random generator like lrand48() for this?
** Because the OP_NewRecno opcode in the VDBE depends on having a very
** good source of random numbers.  The lrand48() library function may
** well be good enough.  But maybe not.  Or maybe lrand48() has some
** subtle problems on some systems that could cause problems.  It is hard
** to know.  To minimize the risk of problems due to bad lrand48()
** implementations, SQLite uses this random number generator based
** on RC4, which we know works very well.
**
** 从RC4 PRNG获取单个8位随机值。执行此例程时必须持有互斥锁。
**
** 为什么不直接使用像lrand48()这样的库随机生成器呢？
** 因为VDBE中的OP_NewRecno操作码依赖于拥有非常好的随机数源。
** lrand48()库函数可能足够好。但也可能不够好。
** 或者lrand48()在某些系统上可能存在一些微妙的问题，可能会导致问题。
** 这很难知道。为了尽量减少由于糟糕的lrand48()实现而导致问题的风险，
** SQLite使用这个基于RC4的随机数生成器，我们知道它工作得非常好。
*/
static int randomByte(){
    int t;

    /* All threads share a single random number generator.
    ** This structure is the current state of the generator.
    **
    ** 所有线程共享一个随机数生成器。
    ** 此结构是生成器的当前状态。
    */
    static struct {
        int isInit;          /* True if initialized */
        int i, j;            /* State variables */
        int s[256];          /* State variables */
    } prng;

    /* Initialize the state of the random number generator once,
    ** the first time this routine is called.  The seed value does
    ** not need to contain a lot of randomness since we are not
    ** trying to do secure encryption or anything like that...
    **
    ** Nothing in this file or anywhere else in SQLite does any kind of
    ** encryption.  The RC4 algorithm is being used as a PRNG (pseudo-random
    ** number generator) not as an encryption device.
    **
    ** 在第一次调用此例程时，初始化随机数生成器的状态一次。
    ** 种子值不需要包含很多随机性，因为我们要做的不是安全加密或类似的事情...
    **
    ** 此文件或SQLite中的其他任何地方都没有进行任何类型的加密。
    ** RC4算法被用作PRNG（伪随机数生成器），而不是加密设备。
    */
    if( !prng.isInit ){
        int i;
        char k[256];
        prng.j = 0;
        prng.i = 0;
        sqliteOsRandomSeed(k);
        for(i=0; i<256; i++){
            prng.s[i] = i;
        }
        for(i=0; i<256; i++){
            int t;
            prng.j = (prng.j + prng.s[i] + k[i]) & 0xff;
            t = prng.s[prng.j];
            prng.s[prng.j] = prng.s[i];
            prng.s[i] = t;
        }
        prng.isInit = 1;
    }

    /* Generate and return single random byte
    **
    ** 生成并返回单个随机字节
    */
    prng.i = (prng.i + 1) & 0xff;
    prng.j = (prng.j + prng.s[prng.i]) & 0xff;
    t = prng.s[prng.i];
    prng.s[prng.i] = prng.s[prng.j];
    prng.s[prng.j] = t;
    t = prng.s[prng.i] + prng.s[prng.j];
    return prng.s[t & 0xff];
}

/*
** Return an random 8-bit integer.
**
** 返回一个随机的8位整数。
*/
int sqliteRandomByte(){
    int r;
    sqliteOsEnterMutex();
    r = randomByte();
    sqliteOsLeaveMutex();
    return r;
}

/*
** Return a random 32-bit integer.  The integer is generated by making
** 4 calls to sqliteRandomByte().
**
** 返回一个随机的32位整数。该整数是通过调用4次sqliteRandomByte()生成的。
*/
int sqliteRandomInteger(){
    int r;
    int i;
    sqliteOsEnterMutex();
    r = randomByte();
    for(i=1; i<4; i++){
        r = (r<<8) + randomByte();
    }
    sqliteOsLeaveMutex();
    return r;
}
